class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'appTitle': 'Credit Manager',
      'customers': 'Customers',
      'addCustomer': 'Add Customer',
      'addCredit': 'Add Credit',
      'addPayment': 'Add Payment',
      'name': 'Name',
      'phone': 'Phone',
      'amount': 'Amount',
      'debt': 'Debt',
      'balance': 'Balance',
      'note': 'Note',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'export': 'Export to PDF',
      'history': 'Transaction History',
      'transactions': 'Transactions',
      'transaction': 'Transaction',
      'credit': 'Credit',
      'payment': 'Payment',
      'balanceCredit': 'Balance Credit',
      'date': 'Date',
      'type': 'Type',
      'currency': 'TND',
      'enterAmount': 'Enter amount',
      'enterName': 'Enter customer name',
      'enterPhone': 'Enter phone number',
      'successCredit': 'Credit added successfully',
      'successPayment': 'Payment added successfully',
      'successCustomer': 'Customer added successfully',
      'error': 'Error',
      'errorAmount': 'Please enter a valid amount',
      'errorName': 'Please enter customer name',
      'keepBalance': 'Keep overpayment as balance',
      'currentDebt': 'Current Debt',
      'exportPDF': 'Export to PDF',
      'exportingPDF': 'Generating PDF...',
      'pdfExported': 'PDF exported successfully',
      'customerDetails': 'Customer Details',
      'noTransactions': 'No transactions yet',
    },
    'fr': {
      'appTitle': 'Gestionnaire de Crédit',
      'customers': 'Clients',
      'addCustomer': 'Ajouter un Client',
      'addCredit': 'Ajouter un Crédit',
      'addPayment': 'Ajouter un Paiement',
      'name': 'Nom',
      'phone': 'Téléphone',
      'amount': 'Montant',
      'debt': 'Dette',
      'balance': 'Solde',
      'note': 'Remarque',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'export': 'Exporter en PDF',
      'history': 'Historique des Transactions',
      'transactions': 'Transactions',
      'transaction': 'Transaction',
      'credit': 'Crédit',
      'payment': 'Paiement',
      'balanceCredit': 'Crédit de Solde',
      'date': 'Date',
      'type': 'Type',
      'currency': 'TND',
      'enterAmount': 'Entrez le montant',
      'enterName': 'Entrez le nom du client',
      'enterPhone': 'Entrez le numéro de téléphone',
      'successCredit': 'Crédit ajouté avec succès',
      'successPayment': 'Paiement ajouté avec succès',
      'successCustomer': 'Client ajouté avec succès',
      'error': 'Erreur',
      'errorAmount': 'Veuillez entrer un montant valide',
      'errorName': 'Veuillez entrer le nom du client',
      'keepBalance': 'Conserver le trop-payé en solde',
      'currentDebt': 'Dette Actuelle',
      'exportPDF': 'Exporter en PDF',
      'exportingPDF': 'Génération du PDF...',
      'pdfExported': 'PDF exporté avec succès',
      'customerDetails': 'Détails du Client',
      'noTransactions': 'Pas de transactions pour le moment',
    },
    'ar': {
      'appTitle': 'مدير الائتمان',
      'customers': 'العملاء',
      'addCustomer': 'إضافة عميل',
      'addCredit': 'إضافة رصيد',
      'addPayment': 'إضافة دفعة',
      'name': 'الاسم',
      'phone': 'الهاتف',
      'amount': 'المبلغ',
      'debt': 'الديون',
      'balance': 'الرصيد',
      'note': 'ملاحظة',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'export': 'تصدير إلى PDF',
      'history': 'سجل المعاملات',
      'transactions': 'المعاملات',
      'transaction': 'المعاملة',
      'credit': 'رصيد',
      'payment': 'دفعة',
      'balanceCredit': 'رصيد الرصيد',
      'date': 'التاريخ',
      'type': 'النوع',
      'currency': 'TND',
      'enterAmount': 'أدخل المبلغ',
      'enterName': 'أدخل اسم العميل',
      'enterPhone': 'أدخل رقم الهاتف',
      'successCredit': 'تم إضافة الرصيد بنجاح',
      'successPayment': 'تمت إضافة الدفعة بنجاح',
      'successCustomer': 'تم إضافة العميل بنجاح',
      'error': 'خطأ',
      'errorAmount': 'يرجى إدخال مبلغ صحيح',
      'errorName': 'يرجى إدخال اسم العميل',
      'keepBalance': 'الاحتفاظ بالدفع الزائد كرصيد',
      'currentDebt': 'الديون الحالية',
      'exportPDF': 'تصدير إلى PDF',
      'exportingPDF': 'جاري إنشاء PDF...',
      'pdfExported': 'تم تصدير PDF بنجاح',
      'customerDetails': 'تفاصيل العميل',
      'noTransactions': 'لا توجد معاملات حتى الآن',
    },
  };

  static String get(String key, String language) {
    return translations[language]?[key] ?? translations['en']?[key] ?? key;
  }
}
